openfaces/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^openface/', include('webopenface.urls')),
    url(r'^admin/', admin.site.urls),
]

webopenface/urls.py
from django.conf.urls import include, url
from webopenface import views

urlpatterns = [
    url(r'^api/', include('webopenface.api_urls')),
    url(r'^$', views.index, name='index'),
    url(r'^preview/$', views.preview, name='preview'),
    url(r'^person/$', views.person, name='person'),
    url(r'^lastframes/$', views.last_frames, name='lastFrames'),
    url(r'^detectedpeople/(?P<pk>[0-9]*)$', views.detected_people, name='detectedPeople'),
    url(r'^addedpeople/$', views.added_people, name='addedPeople'),
    url(r'^addedpeople/(?P<pk>[0-9]*)$', views.person_details, name='personDetails'),
]

webopenface/models.py
from __future__ import unicode_literals
from django.db import models

import timeCalculation


class Person(models.Model):
    uid = models.CharField(max_length=50, blank=True)
    name = models.CharField(max_length=50, )
    add_date = models.DateTimeField(auto_now_add=True, )
    mod_date = models.DateTimeField(auto_now=True, )

    class Meta:
        verbose_name_plural = "people"

    def __unicode__(self):
        return self.name


class PeopleFace(models.Model):
    person = models.ForeignKey(Person, )
    face = models.TextField()

    def __unicode__(self):
        return self.person.name


class Frame(models.Model):
    frame = models.TextField()
    add_date = models.DateTimeField(auto_now_add=True, )

    def __unicode__(self):
        return self.frame[0:100]

    def was_published_recently(self):
        return self.add_date >= timeCalculation.turn_back_time(0.5)

    def save_delete(self):
        objects = Frame.objects.all()
        if objects.count() >= 2000:
            Frame.objects.filter(id__in=objects[:200]).delete()
        self.save()


class DetectedFace(models.Model):
    frame = models.ForeignKey(Frame)
    face = models.TextField()

    def __unicode__(self):
        return self.face[0:100]


class RecognizedPeople(models.Model):
    face = models.ForeignKey(DetectedFace, )
    person = models.ForeignKey(Person, null=True, blank=True)
    probability = models.SmallIntegerField(default=0)
    add_date = models.DateTimeField(auto_now_add=True, )

    def __unicode__(self):
        return str(self.probability)

webopenface/views.py
from django.shortcuts import render
from webopenface.models import Person, Frame


def index(request):
    return render(
        request,
        'webopenface/index.html',
        {
            'added_people': Person.objects.order_by('name')
        }
    )


def preview(request):
    return render(
        request,
        'webopenface/preview.html',
        {
            'latest_frame': Frame.objects.latest('add_date')
        }
    )


def person(request):
    return render(request, 'webopenface/person.html')


def last_frames(request):
    return render(
        request,
        'webopenface/last_frames.html',
        {
            'frames': Frame.objects.order_by('-add_date').all()
        }
    )


def detected_people(request, pk):
    return render(
        request,
        'webopenface/detected_people.html',
        {
            'detected': Frame.objects.get(pk=pk).detectedface_set.all()
        }
    )


def added_people(request):
    return render(
        request,
        'webopenface/added_people.html',
        {
            'people': Person.objects.order_by('-add_date').all()
        }
    )


def person_details(request, pk):
    return render(
        request,
        'webopenface/person_details.html',
        {
            'person': Person.objects.get(pk=pk)
        }
    )

webopenface/templates/webopenface/added-people.html
<div id="addedPeople">
    <h2>Added people</h2>
    {% if added_people %}
        <ul>
        {% for el in added_people %}
            <li>{{ el }}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No people.</p>
    {% endif %}
</div>

webopenface/templates/webopenface/added_people_list.html
<div id="addedPeople">
    <h2>Added people</h2>
    {% if added_people %}
        <ul>
        {% for el in added_people %}
            <li>{{ el }}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No people.</p>
    {% endif %}
</div>

webopenface/templates/webopenface/base.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'webopenface/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'webopenface/css/bootstrap-dialog.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'webopenface/css/bootstrap-toggle.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'webopenface/css/style.css' %}" />
<script src="{% static 'webopenface/js/jquery-3.0.0.min.js' %}"></script>
<script src="{% static 'webopenface/js/bootstrap-toggle.min.js' %}"></script>
<script src="{% static 'webopenface/js/bootstrap.min.js' %}"></script>
<script src="{% static 'webopenface/js/bootstrap-dialog.min.js' %}"></script>


<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/openface">Camera</a></li>
                <li><a href="/openface/preview">Preview</a></li>
                <li><a href="/openface/person">Person</a></li>
                <li><a href="/openface/addedpeople">Added people</a></li>
                <li><a href="/openface/lastframes">Last frames</a></li>
            </ul>
        </div>
    </div>
</nav>

{% block content %}{% endblock%}

{% block staticFile %}{% endblock %}

webopenface/templates/webopenface/detected.html
<div id="detectedPeople" class="col-sm-4">
    <h2>Detected people</h2>
    <div>
        {% if latest_frame.was_published_recently %}
            <ul>
            {% for face in latest_frame.detectedface_set.all %}
                {% for detected_person in face.detectedpeople_set.all %}
                    <li>{{ detected_person.person }} - {{ detected_person.probability }}</li>
                {% endfor %}
            {% endfor %}
            </ul>
        {% else %}
            <p>No camera.</p>
        {% endif %}
    </div>
</div>

webopenface/templates/webopenface/detected_people.html
{% extends 'webopenface/base.html' %}
{% block content %}
    <div class="container">
        <h2 id="dp-head">Last Frames</h2>
        {% if detected %}
            <table id="table" class="table table-responsive">
                <thead>
                    <th>Image</th>
                    <th>People</th>
                </thead>
                <tbody>
                    {% for person in detected %}
                        <tr>
                            <td>
                                <img src="{{ person.face }}">
                            </td>
                            <td>
                                <ul>
                                    {% for el in person.detectedpeople_set.all %}
                                        <li>{{ el.person.name }}</li>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No frame.</p>
        {% endif %}
    </div>
{% endblock %}


{% block staticFile %}
    {% load staticfiles %}
{#    <script src="{% static 'webopenface/js/last-frames.js' %}"></script>#}
{% endblock %}

webopenface/templates/webopenface/index.html
{% extends 'webopenface/base.html' %}

{% block content %}
    <div class="container" id="mainPage">
        <div class="header col-sm-8">
            {% include 'webopenface/video-src.html' %}

            {% include 'webopenface/video-result.html' %}

        {% include 'webopenface/add-perosn.html' %}
        </div>

        {% include 'webopenface/detected.html' %}
    </div>
        {% include 'webopenface/added_people_list.html' %}
{% endblock %}

{% block staticFile %}
    {% load staticfiles %}
    <script src="{% static 'webopenface/js/main.js' %}"></script>
{% endblock %}

webopenface/templates/webopenface/last_frames.html
{% extends 'webopenface/base.html' %}
{% block content %}
    <div class="container">
        <h2 id="lf-head">Last frame</h2>
        {% if frames %}
            <table id="table" class="display">
                <thead>
                    <th> </th>
                    <th>PK</th>
                    <th>Frame</th>
                    <th>Number of people</th>
                    <th>Added date</th>
                </thead>
                <tbody>
                    {% for el in frames %}

                        <tr>
                            <td> {{ forloop.counter }}</td>
                            <td class="pk">{{ el.id }}</td>
                            <td><img src="{{ el.frame }}"></td>
                            <td>{{ el.detectedface_set.count }}</td>
                            <td>{{ el.add_date }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No frames.</p>
        {% endif %}
    </div>
{% endblock %}


{% block staticFile %}
    {% load staticfiles %}
    <script src="{% static 'webopenface/js/last-frames.js' %}"></script>
    <script src="{% static 'webopenface/js/jquery.dataTables.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'webopenface/css/jquery.dataTables.min.css' %}" />
{% endblock %}

webopenface/templates/webopenface/lastframes.html
{% extends 'webopenface/base.html' %}
{% block content %}
    <div class="container">
        <h2 id="lf-head">Last frames</h2>
        {% if frames %}
            <table id="table" class="table table-responsive">
                <thead>
                    <th> </th>
                    <th>PK</th>
                    <th>Frame</th>
                    <th>Number of people</th>
                    <th>Added date</th>
                </thead>
                <tbody>
                    {% for el in frames %}

                        <tr>
                            <td> {{ forloop.counter }}</td>
                            <td class="pk">{{ el.id }}</td>
                            <td><img src="{{ el.frame }}"></td>
                            <td>{{ el.detectedface_set.count }}</td>
                            <td>{{ el.add_date }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No frames.</p>
        {% endif %}
    </div>
{% endblock %}


{% block staticFile %}
    {% load staticfiles %}
    <script src="{% static 'webopenface/js/lastframes.js' %}"></script>
{% endblock %}

webopenface/templates/webopenface/person.html
{% extends 'webopenface/base.html' %}

{% block content %}
    <div class="container" id="personPage">
        <div class="header">
            {% include 'webopenface/video-src-person.html' %}
        </div>

        {% include 'webopenface/add-perosn.html' %}
    </div>
{% endblock content %}

{% block staticFile %}
    {% load staticfiles %}
    <script src="{% static 'webopenface/js/person.js' %}"></script>
{% endblock %}

webopenface/templates/webopenface/person_details.html
{% extends 'webopenface/base.html' %}
{% block content %}
    <div class="container">
        <h2 id="dp-head">Person Image</h2>
        {% if person %}
            <h2>{{ person.name }}</h2>
            <div class="personImage">
                {% for image in person.peopleface_set.all %}
                    <img src="{{ image.face }}">
                {% endfor %}
            </div>
        {% else %}
            <p>No person.</p>
        {% endif %}
    </div>
{% endblock %}


{% block staticFile %}
    {% load staticfiles %}
    <script src="{% static 'webopenface/js/last-frames.js' %}"></script>
{% endblock %}

webopenface/templates/webopenface/preview.html
{% extends 'webopenface/base.html' %}

{% block content %}
    <div class="container" id="previewPage">
        <div class="header col-sm-8">

            {% include 'webopenface/video-result.html' %}
        </div>

        {% include 'webopenface/detected.html' %}
    </div>
{% endblock %}

{% block staticFile %}
    {% load staticfiles %}
    <script src="{% static 'webopenface/js/preview.js' %}"></script>
    <script src="{% static 'webopenface/js/main.js' %}"></script>
{% endblock %}

webopenface/templates/webopenface/video-result.html
<div id='tab-annotated' class='tab-content current'>
    <div id="detectedFaces">
        {% if latest_frame.was_published_recently %}
            <img id='detectedFacesId' src="{{ latest_frame.frame }}" width='430px'>
        {% else %}
            <img id='detectedFacesId' width='430px'>
        {% endif %}
    </div>
</div>

webopenface/templates/webopenface/video-src-person.html
<div id='tab-preview'>
    <video id="videoel" width="400" height="300"
           preload="auto" loop></video>
</div>

webopenface/templates/webopenface/video-src.html
<div id='tab-preview'>
</div>